### ISSUE TITLE
Chage  HTTPS to HTTP

### ISSUE THREAD

**Issue by GilmarPerez** [qmatic/betwixt#1]
Hello, nice to greet,
I require support to clarify the following questions:
We have a version of the APP working with HTTPS, to make the call to the REST API methods Mobile and we want to change this setting to use HTTP since the Application.
•         I made the following changes in the server Betwixt in app.js file:
1.       Modify the variable:
var https = require ('https') 
by  
var http = require ('http') 
 
 
  
2.       Then, change:
var server = https.createServer(options, app).listen(443, function() {…});
by
var server = http.createServer(app).listen(8080, function() {…});
 
 
 
 
•         When I run the "node app" command, it returns the following message:
info Mon Mar 02 2015 09:09:00 GMT-0430 (Hora estándar de Venezuela)HTTP server listening on port 8080 in development mode
info ws Websocket Server running on port 8080...
 
 
 
 
 
•         However, when I made the request to services method of REST, it returns the following message:
ERR! ws Websocket not connected#1
Communication problem #1
 
 
 
 
I wonder if there is another point that must be present to complete this setup?

**Comment by gavsmi** [comment]
Hi,

The websocket connection from Orchestra requires HTTPS, it will not work over HTTP.

If you want to use HTTP for the API create a separate one but use HTTPS for the websocket.

**Comment by GilmarPerez** [comment]
HI, Gavin

We are fairly new to this type of technology, it is possible you indicate something more detail.

Our problem now is that development works perfectly ANDROID us, but does not work when connected IOS HTTPS

Thanks

**Comment by gavsmi** [comment]
Just change this line:
```javascript
// HTTPS server
var server = https.createServer(options, app).listen(443, function() {
	log.info('', 'HTTPS server listening on port %d in %s mode', this.address().port, app.settings.env);
});
```
to this:
```javascript
var http = require('http');
// HTTP server
var server = http.createServer(app).listen(8080, function() {
	log.info('', 'HTTP server listening on port %d in %s mode', this.address().port, app.settings.env);
});

// HTTPS server
var server = https.createServer(options).listen(443, function() {
	log.info('', 'HTTPS server listening on port %d in %s mode', this.address().port, app.settings.env);
});
```
